CategoriesConcerns.create!([
  {category_id: 3, concern_id: 2},
  {category_id: 1, concern_id: 1},
  {category_id: 4, concern_id: 2},
  {category_id: 4, concern_id: 4},
  {category_id: 4, concern_id: 8},
  {category_id: 4, concern_id: 7},
  {category_id: 7, concern_id: 6},
  {category_id: 8, concern_id: 6},
  {category_id: 8, concern_id: 4},
  {category_id: 4, concern_id: 9},
  {category_id: 5, concern_id: 9},
  {category_id: 5, concern_id: 11},
  {category_id: 6, concern_id: 11},
  {category_id: 4, concern_id: 15},
  {category_id: 5, concern_id: 15},
  {category_id: 6, concern_id: 15},
  {category_id: 5, concern_id: 16},
  {category_id: 9, concern_id: 9},
  {category_id: 11, concern_id: 10},
  {category_id: 12, concern_id: 8},
  {category_id: 13, concern_id: 6},
  {category_id: 13, concern_id: 15},
  {category_id: 14, concern_id: 11},
  {category_id: 15, concern_id: 9},
  {category_id: 18, concern_id: 12},
  {category_id: 19, concern_id: 2},
  {category_id: 20, concern_id: 10},
  {category_id: 21, concern_id: 14},
  {category_id: 22, concern_id: 13},
  {category_id: 23, concern_id: 8},
  {category_id: 24, concern_id: 7},
  {category_id: 25, concern_id: 4},
  {category_id: 15, concern_id: 17},
  {category_id: 14, concern_id: 17},
  {category_id: 19, concern_id: 17},
  {category_id: 18, concern_id: 17},
  {category_id: 17, concern_id: 17},
  {category_id: 25, concern_id: 17},
  {category_id: 20, concern_id: 17},
  {category_id: 22, concern_id: 17},
  {category_id: 21, concern_id: 17},
  {category_id: 23, concern_id: 17},
  {category_id: 24, concern_id: 17},
  {category_id: 26, concern_id: 10},
  {category_id: 27, concern_id: 9},
  {category_id: 28, concern_id: 2},
  {category_id: 29, concern_id: 13},
  {category_id: 30, concern_id: 2},
  {category_id: 30, concern_id: 12},
  {category_id: 31, concern_id: 4},
  {category_id: 4, concern_id: 1},
  {category_id: 5, concern_id: 1},
  {category_id: 6, concern_id: 1},
  {category_id: 10, concern_id: 1},
  {category_id: 17, concern_id: 1},
  {category_id: 3, concern_id: 5},
  {category_id: 32, concern_id: 21},
  {category_id: 33, concern_id: 22},
  {category_id: 34, concern_id: 8},
  {category_id: 36, concern_id: 11},
  {category_id: 37, concern_id: 2},
  {category_id: 38, concern_id: 12},
  {category_id: 39, concern_id: 1},
  {category_id: 40, concern_id: 9},
  {category_id: 41, concern_id: 10},
  {category_id: 42, concern_id: 13},
  {category_id: 43, concern_id: 14},
  {category_id: 44, concern_id: 8},
  {category_id: 31, concern_id: 23},
  {category_id: 8, concern_id: 23},
  {category_id: 6, concern_id: 23},
  {category_id: 46, concern_id: 23},
  {category_id: 47, concern_id: 18},
  {category_id: 48, concern_id: 8},
  {category_id: 49, concern_id: 21},
  {category_id: 49, concern_id: 23},
  {category_id: 50, concern_id: 4}
])
CategoriesServices.create!([
  {category_id: 4, service_id: 16},
  {category_id: 25, service_id: 16},
  {category_id: 17, service_id: 7},
  {category_id: 10, service_id: 7},
  {category_id: 25, service_id: 1},
  {category_id: 8, service_id: 1},
  {category_id: 32, service_id: 18},
  {category_id: 32, service_id: 17},
  {category_id: 33, service_id: 19},
  {category_id: 34, service_id: 20},
  {category_id: 34, service_id: 21},
  {category_id: 34, service_id: 24},
  {category_id: 34, service_id: 27},
  {category_id: 34, service_id: 22},
  {category_id: 34, service_id: 25},
  {category_id: 34, service_id: 23},
  {category_id: 34, service_id: 26},
  {category_id: 34, service_id: 28},
  {category_id: 23, service_id: 24},
  {category_id: 23, service_id: 27},
  {category_id: 23, service_id: 21},
  {category_id: 23, service_id: 22},
  {category_id: 23, service_id: 20},
  {category_id: 23, service_id: 25},
  {category_id: 23, service_id: 23},
  {category_id: 23, service_id: 26},
  {category_id: 23, service_id: 28},
  {category_id: 38, service_id: 29},
  {category_id: 37, service_id: 29},
  {category_id: 36, service_id: 29},
  {category_id: 39, service_id: 29},
  {category_id: 40, service_id: 29},
  {category_id: 41, service_id: 29},
  {category_id: 42, service_id: 29},
  {category_id: 43, service_id: 29},
  {category_id: 44, service_id: 29},
  {category_id: 44, service_id: 27},
  {category_id: 37, service_id: 30},
  {category_id: 36, service_id: 30},
  {category_id: 38, service_id: 30},
  {category_id: 39, service_id: 30},
  {category_id: 40, service_id: 30},
  {category_id: 41, service_id: 30},
  {category_id: 42, service_id: 30},
  {category_id: 43, service_id: 30},
  {category_id: 44, service_id: 30},
  {category_id: 45, service_id: 29},
  {category_id: 45, service_id: 30},
  {category_id: 45, service_id: 31},
  {category_id: 44, service_id: 31},
  {category_id: 44, service_id: 32},
  {category_id: 48, service_id: 34},
  {category_id: 48, service_id: 35},
  {category_id: 48, service_id: 37},
  {category_id: 46, service_id: 38},
  {category_id: 46, service_id: 39},
  {category_id: 49, service_id: 40},
  {category_id: 25, service_id: 7},
  {category_id: 25, service_id: 42},
  {category_id: 50, service_id: 42},
  {category_id: 50, service_id: 43},
  {category_id: 9, service_id: 44},
  {category_id: 15, service_id: 45},
  {category_id: 9, service_id: 46},
  {category_id: 9, service_id: 47},
  {category_id: 40, service_id: 48},
  {category_id: 15, service_id: 49},
  {category_id: 51, service_id: 50},
  {category_id: 9, service_id: 51},
  {category_id: 9, service_id: 52},
  {category_id: 15, service_id: 53},
  {category_id: 9, service_id: 54},
  {category_id: 15, service_id: 55},
  {category_id: 9, service_id: 56},
  {category_id: 15, service_id: 57},
  {category_id: 9, service_id: 57},
  {category_id: 44, service_id: 35}
])
Category.create!([
  {name: "Hair Loss Products", description: "Including head coverings and hair styling services"},
  {name: "Support, CHF", description: "For patients and caregivers"},
  {name: "Caregiver Respite ", description: ""},
  {name: "Comfort Item Donation", description: "Includes blankets and other items"},
  {name: "Pain Management", description: ""},
  {name: "Estate Dispursal ", description: "Estate sale planning, etc"},
  {name: "Life Completion Counselling", description: "For patients and families"},
  {name: "Support, Memory", description: "Memory care, Alzheimer's and Dementia support"},
  {name: "Support, Cancer", description: "Support groups for all cancer varieties "},
  {name: "Support, HIV/AIDS", description: ""},
  {name: "Support, Parkinson's ", description: ""},
  {name: "Support, End of Life/ Bereavement", description: ""},
  {name: "Education, ALS", description: ""},
  {name: "Education,  Memory", description: "Education for Alzheimer's, Dementia and other memory disorders"},
  {name: "Education, Cancer", description: ""},
  {name: "Education, COPD", description: ""},
  {name: "Education, CHF", description: ""},
  {name: "Education, HIV/AIDS", description: ""},
  {name: "Education, Liver Disease", description: ""},
  {name: "Education, Kidney Disease", description: ""},
  {name: "Education, Parkinson's", description: ""},
  {name: "Education, Stroke", description: ""},
  {name: "Education, Caregivers", description: "Information on caregiver self-care, etc"},
  {name: "LGBT Resources", description: ""},
  {name: "Safe Return Products", description: ""},
  {name: "Nutrition, CHF", description: ""},
  {name: "Nutrition, Kidney/Renal", description: "Includes renal diabetic resources"},
  {name: "Smoking Cessation", description: ""},
  {name: "Delivery Services", description: ""},
  {name: "Education, Advanced Care Planning", description: "Includes instructions on filling out advanced directives"},
  {name: "Palliative Care Research and Analytics", description: ""},
  {name: "Parkinson's Advocacy and Community", description: ""},
  {name: "Clinical Trials, ALS", description: ""},
  {name: "Clinical Trials,  CHF", description: ""},
  {name: "Clinical Trials, COPD", description: ""},
  {name: "Clinical Trials, Cancer", description: ""},
  {name: "Clinical Trials, Dementia/ Alzheimer's", description: ""},
  {name: "Clinical Trials, HIV/AIDS", description: ""},
  {name: "Clinical Trials, Kidney Disease", description: ""},
  {name: "Clinical Trials, Liver Disease", description: ""},
  {name: "Clinical Trials, Parkinson's Disese", description: ""},
  {name: "Clinical Trials, Stroke", description: ""},
  {name: "Medicare / Medicaid Information", description: ""},
  {name: "Discount Medication", description: ""},
  {name: "Parkinson Adaptive Equipment and Sports ", description: ""},
  {name: "Family Communication Tools", description: "Tools for organizing information and communicating medical and other needs"},
  {name: "Support, Caregivers", description: ""},
  {name: "Treatment, Dementia/ Alzheimer's", description: ""}
])
Category::HABTM_Concerns.create!([
  {category_id: 3, concern_id: 2},
  {category_id: 1, concern_id: 1},
  {category_id: 4, concern_id: 2},
  {category_id: 4, concern_id: 4},
  {category_id: 4, concern_id: 8},
  {category_id: 4, concern_id: 7},
  {category_id: 7, concern_id: 6},
  {category_id: 8, concern_id: 6},
  {category_id: 8, concern_id: 4},
  {category_id: 4, concern_id: 9},
  {category_id: 5, concern_id: 9},
  {category_id: 5, concern_id: 11},
  {category_id: 6, concern_id: 11},
  {category_id: 4, concern_id: 15},
  {category_id: 5, concern_id: 15},
  {category_id: 6, concern_id: 15},
  {category_id: 5, concern_id: 16},
  {category_id: 9, concern_id: 9},
  {category_id: 11, concern_id: 10},
  {category_id: 12, concern_id: 8},
  {category_id: 13, concern_id: 6},
  {category_id: 13, concern_id: 15},
  {category_id: 14, concern_id: 11},
  {category_id: 15, concern_id: 9},
  {category_id: 18, concern_id: 12},
  {category_id: 19, concern_id: 2},
  {category_id: 20, concern_id: 10},
  {category_id: 21, concern_id: 14},
  {category_id: 22, concern_id: 13},
  {category_id: 23, concern_id: 8},
  {category_id: 24, concern_id: 7},
  {category_id: 25, concern_id: 4},
  {category_id: 15, concern_id: 17},
  {category_id: 14, concern_id: 17},
  {category_id: 19, concern_id: 17},
  {category_id: 18, concern_id: 17},
  {category_id: 17, concern_id: 17},
  {category_id: 25, concern_id: 17},
  {category_id: 20, concern_id: 17},
  {category_id: 22, concern_id: 17},
  {category_id: 21, concern_id: 17},
  {category_id: 23, concern_id: 17},
  {category_id: 24, concern_id: 17},
  {category_id: 26, concern_id: 10},
  {category_id: 27, concern_id: 9},
  {category_id: 28, concern_id: 2},
  {category_id: 29, concern_id: 13},
  {category_id: 30, concern_id: 2},
  {category_id: 30, concern_id: 12},
  {category_id: 31, concern_id: 4},
  {category_id: 4, concern_id: 1},
  {category_id: 5, concern_id: 1},
  {category_id: 6, concern_id: 1},
  {category_id: 10, concern_id: 1},
  {category_id: 17, concern_id: 1},
  {category_id: 3, concern_id: 5},
  {category_id: 32, concern_id: 21},
  {category_id: 33, concern_id: 22},
  {category_id: 34, concern_id: 8},
  {category_id: 36, concern_id: 11},
  {category_id: 37, concern_id: 2},
  {category_id: 38, concern_id: 12},
  {category_id: 39, concern_id: 1},
  {category_id: 40, concern_id: 9},
  {category_id: 41, concern_id: 10},
  {category_id: 42, concern_id: 13},
  {category_id: 43, concern_id: 14},
  {category_id: 44, concern_id: 8},
  {category_id: 31, concern_id: 23},
  {category_id: 8, concern_id: 23},
  {category_id: 6, concern_id: 23},
  {category_id: 46, concern_id: 23},
  {category_id: 47, concern_id: 18},
  {category_id: 48, concern_id: 8},
  {category_id: 49, concern_id: 21},
  {category_id: 49, concern_id: 23},
  {category_id: 50, concern_id: 4}
])
Category::HABTM_Services.create!([
  {category_id: 4, service_id: 16},
  {category_id: 25, service_id: 16},
  {category_id: 17, service_id: 7},
  {category_id: 10, service_id: 7},
  {category_id: 25, service_id: 1},
  {category_id: 8, service_id: 1},
  {category_id: 32, service_id: 18},
  {category_id: 32, service_id: 17},
  {category_id: 33, service_id: 19},
  {category_id: 34, service_id: 20},
  {category_id: 34, service_id: 21},
  {category_id: 34, service_id: 24},
  {category_id: 34, service_id: 27},
  {category_id: 34, service_id: 22},
  {category_id: 34, service_id: 25},
  {category_id: 34, service_id: 23},
  {category_id: 34, service_id: 26},
  {category_id: 34, service_id: 28},
  {category_id: 23, service_id: 24},
  {category_id: 23, service_id: 27},
  {category_id: 23, service_id: 21},
  {category_id: 23, service_id: 22},
  {category_id: 23, service_id: 20},
  {category_id: 23, service_id: 25},
  {category_id: 23, service_id: 23},
  {category_id: 23, service_id: 26},
  {category_id: 23, service_id: 28},
  {category_id: 38, service_id: 29},
  {category_id: 37, service_id: 29},
  {category_id: 36, service_id: 29},
  {category_id: 39, service_id: 29},
  {category_id: 40, service_id: 29},
  {category_id: 41, service_id: 29},
  {category_id: 42, service_id: 29},
  {category_id: 43, service_id: 29},
  {category_id: 44, service_id: 29},
  {category_id: 44, service_id: 27},
  {category_id: 37, service_id: 30},
  {category_id: 36, service_id: 30},
  {category_id: 38, service_id: 30},
  {category_id: 39, service_id: 30},
  {category_id: 40, service_id: 30},
  {category_id: 41, service_id: 30},
  {category_id: 42, service_id: 30},
  {category_id: 43, service_id: 30},
  {category_id: 44, service_id: 30},
  {category_id: 45, service_id: 29},
  {category_id: 45, service_id: 30},
  {category_id: 45, service_id: 31},
  {category_id: 44, service_id: 31},
  {category_id: 44, service_id: 32},
  {category_id: 48, service_id: 34},
  {category_id: 48, service_id: 35},
  {category_id: 48, service_id: 37},
  {category_id: 46, service_id: 38},
  {category_id: 46, service_id: 39},
  {category_id: 49, service_id: 40},
  {category_id: 25, service_id: 7},
  {category_id: 25, service_id: 42},
  {category_id: 50, service_id: 42},
  {category_id: 50, service_id: 43},
  {category_id: 9, service_id: 44},
  {category_id: 15, service_id: 45},
  {category_id: 9, service_id: 46},
  {category_id: 9, service_id: 47},
  {category_id: 40, service_id: 48},
  {category_id: 15, service_id: 49},
  {category_id: 51, service_id: 50},
  {category_id: 9, service_id: 51},
  {category_id: 9, service_id: 52},
  {category_id: 15, service_id: 53},
  {category_id: 9, service_id: 54},
  {category_id: 15, service_id: 55},
  {category_id: 9, service_id: 56},
  {category_id: 15, service_id: 57},
  {category_id: 9, service_id: 57},
  {category_id: 44, service_id: 35}
])
Comment.create!([
  {commenter: "Please", body: "Work", service_id: 22},
  {commenter: "does this ", body: "work", service_id: 50},
  {commenter: "testing comments", body: "this is where I would write some important information to share with other care managers", service_id: 16},
  {commenter: "test again", body: "This is a second comment. What happens when I add it?", service_id: 16}
])
Concern.create!([
  {name: "Cancer", description: "Includes all types", diagnosis: true},
  {name: "CHF", description: "Congestive Heart Failure", diagnosis: true},
  {name: "Caregivers", description: "", diagnosis: false},
  {name: "Financial and Legal Services", description: "", diagnosis: false},
  {name: "Bereavement ", description: "", diagnosis: false},
  {name: "Stroke", description: "", diagnosis: true},
  {name: "Parkinson's Disease", description: "", diagnosis: true},
  {name: "Dementia/ Alzheimer's", description: "All memory disorders", diagnosis: true},
  {name: "HIV/AIDS", description: "", diagnosis: true},
  {name: "ALS", description: "Amyotrophic lateral sclerosis", diagnosis: true},
  {name: "COPD", description: "Chronic obstructive pulmonary disease", diagnosis: true},
  {name: "Kidney Disease", description: "Includes renal diabetic resources", diagnosis: true},
  {name: "Liver Disease", description: "", diagnosis: true},
  {name: "Hospice", description: "", diagnosis: false},
  {name: "Education", description: "Collected information on diagnoses, and other", diagnosis: true},
  {name: "Pharmacy", description: "Medication-related resources", diagnosis: true},
  {name: "Language Services", description: "Any services in languages other than English", diagnosis: false},
  {name: "Advanced Care Planning", description: "", diagnosis: false},
  {name: "Palliative Care Information", description: "Information on palliative. Research, information and policies ", diagnosis: false},
  {name: "Aging", description: "", diagnosis: false},
  {name: "Giving Back", description: "Donation and Volunteerism opportunities ", diagnosis: false}
])
Concern::HABTM_Categories.create!([
  {category_id: 3, concern_id: 2},
  {category_id: 1, concern_id: 1},
  {category_id: 4, concern_id: 2},
  {category_id: 4, concern_id: 4},
  {category_id: 4, concern_id: 8},
  {category_id: 4, concern_id: 7},
  {category_id: 7, concern_id: 6},
  {category_id: 8, concern_id: 6},
  {category_id: 8, concern_id: 4},
  {category_id: 4, concern_id: 9},
  {category_id: 5, concern_id: 9},
  {category_id: 5, concern_id: 11},
  {category_id: 6, concern_id: 11},
  {category_id: 4, concern_id: 15},
  {category_id: 5, concern_id: 15},
  {category_id: 6, concern_id: 15},
  {category_id: 5, concern_id: 16},
  {category_id: 9, concern_id: 9},
  {category_id: 11, concern_id: 10},
  {category_id: 12, concern_id: 8},
  {category_id: 13, concern_id: 6},
  {category_id: 13, concern_id: 15},
  {category_id: 14, concern_id: 11},
  {category_id: 15, concern_id: 9},
  {category_id: 18, concern_id: 12},
  {category_id: 19, concern_id: 2},
  {category_id: 20, concern_id: 10},
  {category_id: 21, concern_id: 14},
  {category_id: 22, concern_id: 13},
  {category_id: 23, concern_id: 8},
  {category_id: 24, concern_id: 7},
  {category_id: 25, concern_id: 4},
  {category_id: 15, concern_id: 17},
  {category_id: 14, concern_id: 17},
  {category_id: 19, concern_id: 17},
  {category_id: 18, concern_id: 17},
  {category_id: 17, concern_id: 17},
  {category_id: 25, concern_id: 17},
  {category_id: 20, concern_id: 17},
  {category_id: 22, concern_id: 17},
  {category_id: 21, concern_id: 17},
  {category_id: 23, concern_id: 17},
  {category_id: 24, concern_id: 17},
  {category_id: 26, concern_id: 10},
  {category_id: 27, concern_id: 9},
  {category_id: 28, concern_id: 2},
  {category_id: 29, concern_id: 13},
  {category_id: 30, concern_id: 2},
  {category_id: 30, concern_id: 12},
  {category_id: 31, concern_id: 4},
  {category_id: 4, concern_id: 1},
  {category_id: 5, concern_id: 1},
  {category_id: 6, concern_id: 1},
  {category_id: 10, concern_id: 1},
  {category_id: 17, concern_id: 1},
  {category_id: 3, concern_id: 5},
  {category_id: 32, concern_id: 21},
  {category_id: 33, concern_id: 22},
  {category_id: 34, concern_id: 8},
  {category_id: 36, concern_id: 11},
  {category_id: 37, concern_id: 2},
  {category_id: 38, concern_id: 12},
  {category_id: 39, concern_id: 1},
  {category_id: 40, concern_id: 9},
  {category_id: 41, concern_id: 10},
  {category_id: 42, concern_id: 13},
  {category_id: 43, concern_id: 14},
  {category_id: 44, concern_id: 8},
  {category_id: 31, concern_id: 23},
  {category_id: 8, concern_id: 23},
  {category_id: 6, concern_id: 23},
  {category_id: 46, concern_id: 23},
  {category_id: 47, concern_id: 18},
  {category_id: 48, concern_id: 8},
  {category_id: 49, concern_id: 21},
  {category_id: 49, concern_id: 23},
  {category_id: 50, concern_id: 4}
])
Provider.create!([
  {name: "Oregon Health and Sciences University ", organization: "American Cancer Society", address1: "3303 SW Bond Ave", address2: "", city: "Portland", state: "Oregon", zip: 97239, phone: "(503) 351-5921", website: "http://cancer.org", contact: ""},
  {name: "Caring Bridge", organization: "www.caringbridge.org", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://caringbridge.org", contact: ""},
  {name: "Lyme Disease Task Force", organization: "www.oregonlyme.com", address1: "", address2: "", city: "", state: "Oregon", zip: nil, phone: "541-410-2585", website: "http://oregonlyme.com", contact: "Theresa Denham"},
  {name: "National Caregiver's Library", organization: "Family Care America", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(804) 327 - 1111", website: "http://caregiverslibrary.org", contact: "info@caregiverslibrary.org"},
  {name: "Oregon Health Decisions", organization: "", address1: "7451 SW Coho Court #101", address2: "", city: "Tualatin", state: "Oregon", zip: 97062, phone: "(503) 692-0894", website: "http://oregonhealthdecisions.org", contact: "Kellie Lapp, Executive Director"},
  {name: "Palliative Care Quality Network ", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(415) 476-0682", website: "http://pcqn.org", contact: ""},
  {name: "American Parkinson Disease Association Inc. ", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 223-2732 ", website: "http://apdaparkinson.org", contact: ""},
  {name: "The Michael J. Fox Foundation for Parkinson's Research", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 708-7644", website: "http://michaeljfox.org", contact: ""},
  {name: "National Parkinson Foundation Inc. ", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://parkinson.org", contact: ""},
  {name: "The Parkinson Alliance", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 579 - 8440", website: "http://parkinsonalliance.net", contact: ""},
  {name: "Parkinson's Action Network", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 850-4726", website: "http://parkinsonsaction.org", contact: ""},
  {name: "Parkinson's Disease Foundation", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 457-6676", website: "http://pdf.org", contact: ""},
  {name: "Movement Disorder Society", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(414) 276-2145", website: "http://movementdisorders.org", contact: ""},
  {name: "The Parkinson's Institute and Clinical Center", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 655-2273", website: "http://thepi.org", contact: ""},
  {name: "Parkinson's Health", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "www.parkinsonshealth.com", contact: ""},
  {name: "CenterWatch ", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(866) 219-3440", website: "http://centerwatch.com", contact: ""},
  {name: "ClinicalTrials.gov", organization: "National Institute of Health", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://clinicaltrials.gov", contact: ""},
  {name: "Natinal Institute of Neurological Disorders and Stroke", organization: "National Institute of Health", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://www.ninds.nih.gov/", contact: ""},
  {name: "Parkinson's Study Group", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://parkinson-study-group.org/", contact: ""},
  {name: "Together Rx Access", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://www.togetherrxaccess.com/", contact: ""},
  {name: "Able Data", organization: "National Institute on Disability and Rehabilitation Research", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 227-0216", website: "http://abledata.com", contact: ""},
  {name: "Adaptive Sports Association", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(970) 385-2163", website: "http://asadurango.org/", contact: ""},
  {name: "National Sports Center for the Disabled", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(970) 726-1540", website: "http://www.nscd.org/", contact: ""},
  {name: "National Registry of Rehabilitation Technology Suppliers", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://nrrts.org", contact: ""},
  {name: "Center for Medicare and Medicaid Services", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 633-4227", website: "http://cms.gov", contact: ""},
  {name: "Medicare.gov", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://medicare.gov", contact: ""},
  {name: "Elder Issues - Life Ledger", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://elderissues.com", contact: ""},
  {name: "Family Caregiver Alliance", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 445-8106", website: "http://caregiver.org", contact: ""},
  {name: "National Family Caregivers Association", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 896-3650", website: "http://thefamilycaregiver.org", contact: ""},
  {name: "Caregiving.com", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "", website: "http://caregiving.com", contact: ""},
  {name: "Alzheimer's Association ", organization: "", address1: "", address2: "", city: "", state: "Online", zip: nil, phone: "(800) 272-3900", website: "http://alz.org", contact: ""},
  {name: "Alzheimer's Association of Oregon", organization: "Alzheimer's Association", address1: "", address2: "", city: "", state: "Oregon", zip: nil, phone: "", website: "http://www.alz.org/oregon/", contact: ""},
  {name: "Alzheimer's Association of Washington", organization: "Alzheimer's Association", address1: "", address2: "", city: "", state: "Washington", zip: nil, phone: "", website: "http://www.alz.org/alzwa/", contact: ""},
  {name: "Northwest Parkinson's Foundation", organization: "", address1: "", address2: "", city: "Seattle", state: "Washington", zip: nil, phone: "", website: "http://nwpf.org", contact: ""}
])
ProvidersServices.create!([
  {provider_id: 1, service_id: 1},
  {provider_id: 3, service_id: 4}
])
Request.create!([
  {title: "This is a test", req_type: "Comment/Suggestion", body: "this is only a test", parent_type: "Belongs to a Provider", parent_name: "testing", user: "Tracy", email: "testing@email.com", note: "these are some notes\r\n\r\nthese are some more", resolved: false}
])
Service.create!([
  {title: "Parkinson Information and Research", description: "Foundation that provides information, research and fundraising opportunities. Includes a blog. ", provider_id: 17, refcount: 1},
  {title: "Personal Website to Connect with Loved Ones", description: "Way to share information, updates, photos, memories, etc. to include loved ones, and as an alternative to making difficult phone calls", provider_id: 3, refcount: 0},
  {title: "Lyme Disease Support Groups ", description: "Support groups in Bend, Southern Oregon, Mid-Valley, Portland and Hood River, with times and contact information", provider_id: 4, refcount: 0},
  {title: "Cancer Resource Center", description: "Provides cancer information, and referrals to community programs and resources staffed by volunteers for individuals affected by cancer. No appointment necessary", provider_id: 1, refcount: 0},
  {title: "Lyme Disease Programs Classes and Events", description: "Currently none scheduled, check website for updates", provider_id: 4, refcount: 0},
  {title: "Wigs, Free or Reduced Cost", description: "Provides free wigs, hats, scarves and turbans to cancer patients. Items vary depending on availability. ", provider_id: 1, refcount: 0},
  {title: "Digital Library of Caregiving Information/ Resources", description: "Wealth of information for caregivers on many different topics", provider_id: 14, refcount: 0},
  {title: "Advanced Care Planning Guide", description: "", provider_id: 15, refcount: 0},
  {title: "Advanced Care Training", description: "", provider_id: 15, refcount: 0},
  {title: "Palliative Care Research Analytics", description: "Defining and promoting quality palliative care, palliative care clinical outcomes", provider_id: 16, refcount: 0},
  {title: "Parkinson Information and Fundraising ", description: "", provider_id: 18, refcount: 0},
  {title: "Parkinson Information and News", description: "", provider_id: 19, refcount: 0},
  {title: "Parkinson News, Events, Research", description: "", provider_id: 20, refcount: 0},
  {title: "Parkinson Activism, Events and Research", description: "", provider_id: 21, refcount: 0},
  {title: "Parkinson Information, Living with Parkinson's", description: "", provider_id: 22, refcount: 0},
  {title: "Parkinson/Movement Disorder Research", description: "", provider_id: 23, refcount: 0},
  {title: "Parkinson Clinical Trials, Resources and Information", description: "", provider_id: 24, refcount: 0},
  {title: "Tips and Tools for Living with Parkinson's", description: "Has animated illustrations about PD, and free registration for Life in Balance Newsletter", provider_id: 25, refcount: 0},
  {title: "Clinical Trials", description: "Clinical trials listed by state and condition ", provider_id: 26, refcount: 0},
  {title: "Clinical Trials", description: "Privately and publicly supported clinical trials ", provider_id: 27, refcount: 0},
  {title: "Clinical Trials for Neurological Disorders and Stroke", description: "", provider_id: 28, refcount: 0},
  {title: "Parkinson's Clinical Trials and Research", description: "", provider_id: 29, refcount: 0},
  {title: "Prescription Savings", description: "", provider_id: 30, refcount: 0},
  {title: "Adaptive Equipment and Assistive Technology", description: "", provider_id: 31, refcount: 0},
  {title: "Information on Adaptive Sporting ", description: "", provider_id: 32, refcount: 0},
  {title: "Adaptive Sports", description: "", provider_id: 33, refcount: 0},
  {title: "Fitting Wheelchairs and Mobility Equipment", description: "", provider_id: 34, refcount: 0},
  {title: "Medicare / Medicaid Information", description: "", provider_id: 35, refcount: 0},
  {title: "Medicare Information ", description: "", provider_id: 36, refcount: 0},
  {title: "Compiling Medical Records", description: "Resource for compiling and managing personal medical files - fee associated", provider_id: 37, refcount: 0},
  {title: "Public Programs for Family Caregivers", description: "State-by-state breakdown of services ", provider_id: 38, refcount: 0},
  {title: "Caregiver Support , Education and Advocacy", description: "", provider_id: 39, refcount: 0},
  {title: "Caregiving Online Support Community", description: "", provider_id: 40, refcount: 0},
  {title: "Alzheimer's HelpLine 24/7", description: "", provider_id: 41, refcount: 0},
  {title: "Alzheimer's Research Information", description: "", provider_id: 41, refcount: 0},
  {title: "Customized Action Plan", description: "", provider_id: 41, refcount: 0},
  {title: "Alzheimer's Clinical Trial Matching", description: "", provider_id: 1, refcount: 0},
  {title: "Alzheimer's General Disease Information ", description: "", provider_id: 41, refcount: 0},
  {title: "Alzheimer's Diagnostic and Treatment Options", description: "", provider_id: 41, refcount: 0},
  {title: "Alzheimer's Support Groups in Oregon", description: "List of groups by city in Oregon ", provider_id: 42, refcount: 0},
  {title: "Alzheimer's Community Events in Oregon", description: "", provider_id: 42, refcount: 0},
  {title: "Alzheimer's Regional Education Events in Oregon", description: "", provider_id: 42, refcount: 0},
  {title: "Alzheimer's Support Groups in Washington", description: "", provider_id: 43, refcount: 0},
  {title: "Alzheimer's Regional Education Events in Washington", description: "", provider_id: 43, refcount: 0},
  {title: "Alzheimer's Community Events in Washington", description: "", provider_id: 43, refcount: 0},
  {title: "Parkinson's Resources and Information", description: "Organization serving the greater Seattle area with specialty care, education and support resources and events", provider_id: 44, refcount: 0},
  {title: "Alzheimer's Support Groups", description: "", provider_id: 41, refcount: 0}
])
Service::HABTM_Categories.create!([
  {category_id: 4, service_id: 16},
  {category_id: 25, service_id: 16},
  {category_id: 17, service_id: 7},
  {category_id: 10, service_id: 7},
  {category_id: 25, service_id: 1},
  {category_id: 8, service_id: 1},
  {category_id: 32, service_id: 18},
  {category_id: 32, service_id: 17},
  {category_id: 33, service_id: 19},
  {category_id: 34, service_id: 20},
  {category_id: 34, service_id: 21},
  {category_id: 34, service_id: 24},
  {category_id: 34, service_id: 27},
  {category_id: 34, service_id: 22},
  {category_id: 34, service_id: 25},
  {category_id: 34, service_id: 23},
  {category_id: 34, service_id: 26},
  {category_id: 34, service_id: 28},
  {category_id: 23, service_id: 24},
  {category_id: 23, service_id: 27},
  {category_id: 23, service_id: 21},
  {category_id: 23, service_id: 22},
  {category_id: 23, service_id: 20},
  {category_id: 23, service_id: 25},
  {category_id: 23, service_id: 23},
  {category_id: 23, service_id: 26},
  {category_id: 23, service_id: 28},
  {category_id: 38, service_id: 29},
  {category_id: 37, service_id: 29},
  {category_id: 36, service_id: 29},
  {category_id: 39, service_id: 29},
  {category_id: 40, service_id: 29},
  {category_id: 41, service_id: 29},
  {category_id: 42, service_id: 29},
  {category_id: 43, service_id: 29},
  {category_id: 44, service_id: 29},
  {category_id: 44, service_id: 27},
  {category_id: 37, service_id: 30},
  {category_id: 36, service_id: 30},
  {category_id: 38, service_id: 30},
  {category_id: 39, service_id: 30},
  {category_id: 40, service_id: 30},
  {category_id: 41, service_id: 30},
  {category_id: 42, service_id: 30},
  {category_id: 43, service_id: 30},
  {category_id: 44, service_id: 30},
  {category_id: 45, service_id: 29},
  {category_id: 45, service_id: 30},
  {category_id: 45, service_id: 31},
  {category_id: 44, service_id: 31},
  {category_id: 44, service_id: 32},
  {category_id: 48, service_id: 34},
  {category_id: 48, service_id: 35},
  {category_id: 48, service_id: 37},
  {category_id: 46, service_id: 38},
  {category_id: 46, service_id: 39},
  {category_id: 49, service_id: 40},
  {category_id: 25, service_id: 7},
  {category_id: 25, service_id: 42},
  {category_id: 50, service_id: 42},
  {category_id: 50, service_id: 43},
  {category_id: 9, service_id: 44},
  {category_id: 15, service_id: 45},
  {category_id: 9, service_id: 46},
  {category_id: 9, service_id: 47},
  {category_id: 40, service_id: 48},
  {category_id: 15, service_id: 49},
  {category_id: 51, service_id: 50},
  {category_id: 9, service_id: 51},
  {category_id: 9, service_id: 52},
  {category_id: 15, service_id: 53},
  {category_id: 9, service_id: 54},
  {category_id: 15, service_id: 55},
  {category_id: 9, service_id: 56},
  {category_id: 15, service_id: 57},
  {category_id: 9, service_id: 57},
  {category_id: 44, service_id: 35}
])
